version: "3.5"

services:
  php_fpm:
      build: .
      container_name: chess_data_php_fpm
      restart: always
      working_dir: /usr/share/nginx/pgn-chess-data
      networks:
          - chess_data
      volumes:
          - ./:/usr/share/nginx/pgn-chess-data
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
      image: mysql:5.7
      container_name: chess_data_mysql
      restart: always
      networks:
          - chess_data
      volumes:
          - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${DB_NAME}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  chess_data:
    driver: bridge
