site_name: Chess Data
site_url: https://chesslablab.github.io/chess-data/
nav:
  - Home: index.md
  - Installation: installation.md
  - Seed the Tables with Data: seed-the-tables-with-data.md
theme: readthedocs
